### ISSUE TITLE
Suggestion: Add an option to generate linux mkdir / touch commands

### ISSUE THREAD

**Issue by sbrl** [Webiny/FolderBuilder#6]
It would be awesome if you could automatically generate a set of linux commands to create the folder structure. Then I could paste them into my Console/Terminal/SSH session.

Example:

```
mkdir test
touch test/testing.php
```

**Comment by Swader** [comment]
Great idea. I'm on it.

**Comment by sbrl** [comment]
@Swader Thanks so much :)

**Comment by Swader** [comment]
@sbrl all done, more or less. In latest master branch - use locally if you want the feature while you wait for the guys in charge to put the change online :)
